services:
  db:
    image: mysql:latest
    
    container_name: mysql_container
    
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_DATABASE: 'myfinancedb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin@admin'
      MYSQL_ROOT_PASSWORD: 'admin@admin'
    
    volumes:
      - mysql_data:/var/lib/mysql
    
    command: ['--default-authentication-plugin=mysql_native_password']
    
    restart: unless-stopped

volumes:
  mysql_data:
