services:
  web: 
    build: .
    container_name: myfinanceapi
    command: >
      sh -c "dockerize -wait tcp://db:3306 -timeout 30s &&
      python manage.py migrate &&
      gunicorn api.wsgi:application --bind 0.0.0.0:8000"

    ports: 
      - "8000:8000"
    depends_on: 
      - db 
  
  db:
    image: mysql:latest

    container_name: myfinancedb
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_DATABASE: 'myfinancedb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin@admin'
      MYSQL_ROOT_PASSWORD: 'admin@admin'
    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
