# Generated by Django 5.0.3 on 2024-04-08 15:18

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=255, validators=[finance.models.validate_category]),
        ),
    ]
