# Generated by Django 5.0.3 on 2024-04-02 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='membercategorymodel',
            options={'verbose_name': 'Member and Category', 'verbose_name_plural': 'Members and Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='membercategorymodel',
            unique_together={('member', 'category')},
        ),
    ]
