# Generated by Django 5.0.3 on 2024-04-04 01:53

import datetime
import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[finance.models.validate_value_spent])),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('member_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_category', to='finance.membercategorymodel')),
            ],
        ),
    ]
